#!/usr/bin/env node

/**
 * Build script for fast-fs-hash.
 *
 * 1. Bundles `index.ts` into `dist/index.cjs` via rolldown.
 * 2. Generates thin ESM wrapper (`.mjs`) that re-exports from the CJS bundle.
 * 3. Generates type declarations via tsc + rollup-plugin-dts.
 */

import { exec } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { promisify } from "node:util";
import { DIST_DIR, elapsed, logInfo, logOk, logTitle, PKG_DIR, ROOT_DIR, SRC_DIR } from "./lib/utils.js";

const execAsync = promisify(exec);

const t0 = performance.now();

mkdirSync(DIST_DIR, { recursive: true });

// ─── Step 1: CJS bundle ─────────────────────────────────────────────────

async function buildBundle() {
  const s = performance.now();
  const { build } = await import("rolldown");

  await build({
    input: { index: resolve(SRC_DIR, "index.ts") },
    external: [/^node:/, /^@fast-fs-hash\//],
    output: {
      dir: DIST_DIR,
      format: "cjs",
      entryFileNames: "[name].cjs",
      sourcemap: true,
      comments: { jsdoc: true, annotation: true, legal: true },
    },
    resolve: {
      extensions: [".ts", ".js"],
    },
    platform: "node",
    optimization: {
      inlineConst: { mode: "all", pass: 3 },
    },
    treeshake: true,
  });

  logOk(`index.cjs bundle (${elapsed(s)})`);
}

// ─── ESM wrapper (thin re-export from CJS) ──────────────────────────────

function generateESMWrapper() {
  const s = performance.now();
  const src = readFileSync(resolve(SRC_DIR, "index.ts"), "utf8");
  const valueExports = [];

  for (const match of src.matchAll(/^export\s+\{([^}]+)\}/gm)) {
    const line = match[0];
    if (/^export\s+type\s+\{/.test(line)) {
      continue;
    }
    for (const name of match[1].split(",")) {
      const trimmed = name.trim();
      if (trimmed) {
        const parts = trimmed.split(/\s+as\s+/);
        valueExports.push(parts[parts.length - 1].trim());
      }
    }
  }

  for (const match of src.matchAll(/^export\s+const\s+\{([^}]+)\}\s*=/gm)) {
    for (const name of match[1].split(",")) {
      const trimmed = name.trim();
      if (trimmed) {
        const parts = trimmed.split(/\s*:\s*/);
        const exported = parts[parts.length - 1].trim();
        if (exported && !valueExports.includes(exported)) {
          valueExports.push(exported);
        }
      }
    }
  }

  for (const match of src.matchAll(/^export\s+(?:const|function|class)\s+(\w+)/gm)) {
    const name = match[1];
    if (!valueExports.includes(name)) {
      valueExports.push(name);
    }
  }

  if (valueExports.length === 0) {
    throw new Error("No value exports found in index.ts — ESM wrapper generation failed");
  }

  const lines = [
    "// Auto-generated ESM wrapper — re-exports from the CJS bundle to avoid dual instances.",
    "// Do not edit manually; regenerated by scripts/build-ts.js.",
    "",
    'import _cjs_mod from "./index.cjs";',
    "",
    "export const {",
    ...valueExports.map((name) => `  ${name},`),
    "} = _cjs_mod;",
    "",
  ];

  writeFileSync(resolve(DIST_DIR, "index.mjs"), lines.join("\n"));
  logInfo(`ESM exports: ${valueExports.join(", ")}`);
  logOk(`ESM wrapper (${elapsed(s)})`);
}

// ─── Type declarations ────────────────────────────────────────────────────

async function generateTypeDeclarations() {
  const s = performance.now();

  const tmpDir = resolve(PKG_DIR, "dist-types-tmp");
  rmSync(tmpDir, { recursive: true, force: true });

  try {
    await execAsync(`npx tsc -p ${JSON.stringify(resolve(ROOT_DIR, "tsconfig.build.json"))}`, {
      cwd: PKG_DIR,
    }).catch((err) => {
      const msg = (err.stdout || err.stderr || err.message || "").trim();
      if (msg) {
        console.error(msg);
      }
      throw err;
    });

    const { rollup } = await import("rollup");
    const { dts } = await import("rollup-plugin-dts");

    const bundle = await rollup({
      input: resolve(tmpDir, "index.d.ts"),
      plugins: [dts({ respectExternal: true })],
      external: [/^node:/],
    });
    await bundle.write({ file: resolve(DIST_DIR, "index.d.ts"), format: "es" });
    await bundle.close();

    writeFileSync(resolve(DIST_DIR, "index.d.cts"), 'export * from "./index.js";\n');
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }

  logOk(`Type declarations (${elapsed(s)})`);
}

// ─── Run ──────────────────────────────────────────────────────────────────

logTitle("Building TypeScript...");

// Remove stale files from previous builds
for (const f of readdirSync(DIST_DIR)) {
  if (
    f.startsWith("_bootstrap") ||
    (f.startsWith("_shared-") && (f.endsWith(".cjs") || f.endsWith(".cjs.map"))) ||
    (f.startsWith("FileHashCache-") && (f.endsWith(".js") || f.endsWith(".js.map")))
  ) {
    rmSync(resolve(DIST_DIR, f), { force: true });
  }
}

await buildBundle();
generateESMWrapper();
await generateTypeDeclarations();

logOk(`TS build completed (${elapsed(t0)})`);
